export const foodItems = [
  {
    id: 0,
    name: 'Margherita Pizza',
    description: 'Classic pizza with tomato sauce, mozzarella, and basil',
    price: 12.99,
    rating: 4.5,
    category: 'Pizza Items',
    prepTime: '20-30 min',
    calories: 850,
    image: require('../assets/pizza.jpg'),
  },
  {
    id: 1,
    name: 'Cheese Pizza',
    description: 'Classic pizza with tomato sauce, mozzarella, and basil',
    price: 12.99,
    rating: 4.5,
    category: 'Pizza Items',
    prepTime: '20-30 min',
    calories: 850,
    image: require('../assets/pizza.jpg'),
  },
   {
    id: 2,
    name: 'steam momos',
    description: 'Classic pizza with tomato sauce, mozzarella, and basil',
    price: 2.99,
    rating: 4.5,
    category: 'momos Items',
    prepTime: '20-30 min',
    calories: 850,
    image: require('../assets/steammomos.jpg'),
  },
   {
    id: 3,
    name: 'hamburger',
    description: 'burger with chicken,cabbage leaves and tomato',
    price: 12,
    rating: 4.5,
    category: 'Burger Items',
    prepTime: '20-30 min',
    calories: 850,
    image: require('../assets/hamburger.jpg'),
  },
  
  {
    id: 4,
    name: 'pizza',
    description: 'pizza with extra cheese',
    price: 12.99,
    rating: 4.5,
    category: 'Pizza Items',
    prepTime: '20-30 min',
    calories: 850,
    image: require('../assets/pizza.jpg'),
  },
  {
    id: 5,
    name: 'Hakaa Noodles',
    description: 'keema noodles  with tomato sauce, mozzarella, and basil',
    price: 7.99,
    rating: 4.5,
    category: 'Noodels Items',
    prepTime: '20-30 min',
    calories: 850,
    image: require('../assets/chowmein.jpg'),
  },
  {
    id: 6,
    name: 'chicken chilli',
    description: 'chicken chillyy with tomato sauce and veggies',
    price: 9.99,
    rating: 4.5,
    category: 'others items',
    prepTime: '20-30 min',
    calories: 850,
    image: require('../assets/chicken_chilli.jpg'),
  },
  {
    id: 7,
    name: 'mmexicano Pizza',
    description: 'Classic pizza with tomato sauce and basil',
    price: 10.99,
    rating: 4.5,
    category: 'pizza Items',
    prepTime: '20-30 min',
    calories: 850,
    image: require('../assets/pizza.jpg'),
  },
  {
    id: 8,
    name: 'Margherita Pizza',
    description: 'Classic pizza with tomato sauce, mozzarella, and basil',
    price: 7.99,
    rating: 4.5,
    category: 'Burger Items',
    prepTime: '20-30 min',
    calories: 850,
    image: require('../assets/pizza.jpg'),
  },
  {
    id: 9,
    name: 'cheese Pizza',
    description: 'Classic pizza with tomato sauce, mozzarella, and basil',
    price: 9.99,
    rating: 4.5,
    category: 'Pizza Items',
    prepTime: '20-30 min',
    calories: 850,
    image: require('../assets/cheesepizza.jpg'),
  },
  {
    id: 10,
    name: 'chicken chowmein',
    description: 'chicken chowmein with fried chicken and vegetables',
    price: 12.99,
    rating: 4.5,
    category: 'Noodels Items',
    prepTime: '20-30 min',
    calories: 850,
    image: require('../assets/chowmein.jpg'),
  },

  {
    id: 11,
    name: 'c momos',
    description: 'c momos with hot tomato sauce',
    price: 12.99,
    rating: 4.5,
    category: 'Momos Items',
    prepTime: '20-30 min',
    calories: 850,
    image: require('../assets/c momos.jpeg'),
  },
 
  {
    id: 12,
    name: 'butternaan',
    description: 'butter naan with curry',
    price: 12.99,
    rating: 4.5,
    category: 'pizza Items',
    prepTime: '20-30 min',
    calories: 850,
    image: require('../assets/butternaan.jpeg'),

    },

    {
    id: 13,
    name: 'chickenroast',
    description: 'chicken roast bbq with spicy masala',
    price: 12.99,
    rating: 4.5,
    category: 'Others Items',
    prepTime: '20-30 min',
    calories: 850,
    image: require('../assets/chickenroast.jpeg'),

    },

     {
    id: 14,
    name: 'Biryani',
    description: 'Classic pizza with tomato sauce, mozzarella, and basil',
    price: 12.99,
    rating: 4.5,
    category: 'Others Items',
    prepTime: '20-30 min',
    calories: 850,
    image: require('../assets/biryani.jpeg'),

     },
     
   {
    id: 15,
    name: 'Mutton choila',
    description: 'choila with spicy masala',
    price: 12.99,
    rating: 4.5,
    category: 'Others Items',
    prepTime: '20-30 min',
    calories: 850,
    image: require('../assets/choila.jpg'),

    },
];

export const categories = [
  { id: 1, name: 'Pizza Items' },
  { id: 2, name: 'Burger Items' },
  { id: 3, name: 'Noodels Items' },
  { id: 4, name: 'Momos Items' },
  { id: 5, name: 'Others Items' },
  { id: 6, name: 'Biryani Items' },
];